-- Table principale pour stocker les utilisateurs dans Supabase.
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  age integer not null check (age > 0),
  residence text not null
);


-- Données de départ pour avoir immédiatement 4 utilisateurs en base.
insert into public.users (name, age, residence)
values
  ('Amine', 24, 'Casablanca'),
  ('Sara', 29, 'Rabat'),
  ('Yassine', 31, 'Marrakech'),
  ('Lina', 22, 'Tanger')
on conflict do nothing;
